apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
    app: minio
spec:
  project: script-execution-manager
  source:
    repoURL: https://github.com/Tanmay71710/learning-and-implementation
    targetRevision: staging
    path: environments/staging/minio-deployment.yaml
  destination:
    server: https://staging.kubernetes.example.com
    namespace: minio-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true