apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "script-execution-manager.fullname" . }}-config
  labels:
    {{- include "script-execution-manager.labels" . | nindent 4 }}
data:
  flaskEnv: {{ .Values.config.flaskEnv | quote }}
  flaskDebug: {{ .Values.config.flaskDebug | quote }}
  jenkinsJobName: {{ .Values.config.jenkinsJobName | quote }}
  artifactoryRepository: {{ .Values.config.artifactoryRepository | quote }}
  logLevel: {{ .Values.config.logLevel | quote }}
  maxWorkers: {{ .Values.config.maxWorkers | quote }}
  timeout: {{ .Values.config.timeout | quote }}