apiVersion: v1
kind: Secret
metadata:
  name: {{ include "script-execution-manager.fullname" . }}-secrets
  labels:
    {{- include "script-execution-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
  jenkinsUrl: {{ .Values.secrets.jenkinsUrl | quote }}
  jenkinsUsername: {{ .Values.secrets.jenkinsUsername | quote }}
  jenkinsPassword: {{ .Values.secrets.jenkinsPassword | quote }}
  artifactoryUrl: {{ .Values.secrets.artifactoryUrl | quote }}
  artifactoryUsername: {{ .Values.secrets.artifactoryUsername | quote }}
  artifactoryPassword: {{ .Values.secrets.artifactoryPassword | quote }}
  artifactoryApiKey: {{ .Values.secrets.artifactoryApiKey | quote }}