apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-execution-manager
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: script-execution-manager
        resources:
          requests:
            memory: "384Mi"
            cpu: "350m"
          limits:
            memory: "768Mi"
            cpu: "750m"