apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: script-execution-manager-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
spec:
  project: script-execution-manager
  source:
    repoURL: https://github.com/Tanmay71710/learning-and-implementation
    targetRevision: develop
    path: environments/dev/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: script-execution-manager-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/replicas
  revisionHistoryLimit: 3
  info:
    - name: Application
      value: Script Execution Manager
    - name: Environment
      value: Development
    - name: Owner
      value: DevOps Team